"""
Django settings for Blog project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4kib(v1go^q#frt9%v@xen5-1pwce2s3@@&12nad7u3&8i-*vi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['www.*****88.top']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mptt', #评论树形插件
    'notifications', # 消息通知插件
    'pure_pagination',  # 分页插件
    'taggit', # 标签插件
    'front_end.apps.FrontEndConfig',
    "back_end",
    "notice",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'blog',
		'USER': 'root',
		'PASSWORD': '*****',
		'HOST': '127.0.0.1',
		'PORT': 3306,
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
	}
}

# 添加以下代码,取消外键检查
#         'OPTIONS': {
#             "init_command": "SET foreign_key_checks = 0;",
#         }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, 'static'),
]

# 静态文件收集目录
# STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')


# 处理浏览器关闭就自动退出
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE=True

# django-taggit不区分大小写的查找现有标签
TAGGIT_CASE_INSENSITIVE = True

# 处理Django3.0中XFrameOptionsMiddleware默认为'DENY'类型
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 如果没有登录，默认跳转到那个URL
LOGIN_URL = "/login/"

# 使用django自带的user表，这里重构它
AUTH_USER_MODEL = 'front_end.UserInfo'
# 自定义登录认证配置，声明重写方法
AUTHENTICATION_BACKENDS = [
	'front_end.views.CustomBackend',
]

# Django用户上传的都叫media文件,静态文件
MEDIA_URL = "/media/"

# media配置，用户上传的文件都默认放在这个文件夹下
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 邮件验证设置(明码发送邮件)
# 打开ssl协议
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.126.com'  # 服务器
EMAIL_PORT = 465   # 一般情况下都为25（明码端口）
EMAIL_HOST_USER = '******@126.com'  # 帐号
EMAIL_HOST_PASSWORD = '*********'  # 密码
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_FROM = '**********@126.com'



# django-pure-pagination 分页设置
PAGINATION_SETTINGS = {
	'PAGE_RANGE_DISPLAYED': 2,  # 分页条当前页前后应该显示的总页数（两边均匀分布，因此要设置为偶数），
	'MARGIN_PAGES_DISPLAYED': 2,  # 分页条开头和结尾显示的页数(有两个数字，即1，2...5，6)
	'SHOW_FIRST_PAGE_WHEN_INVALID': True,  # 当请求了不存在页，显示第一页
}

